services:
  authentication-service:
    build:
      context: ../../  # Monorepo root
      dockerfile: services/service-authentication/Dockerfile.development
    ports:
      - "${SERVICE_AUTHENTICATION_PORT}:3001"  # Host:Container
    volumes:
      - ../../services/service-authentication:/app
      - /app/node_modules
    env_file:
      - ../../services/service-authentication/.env.development
    command: yarn dev
    depends_on:
      - redis

  mailing-service:
    build:
      context: ../../  # Monorepo root
      dockerfile: services/service-mailing/Dockerfile.development
    ports:
      - "${SERVICE_MAILING_PORT}:4000"  # Host:Container
    volumes:
      - ../../services/service-mailing:/app
      - /app/node_modules
    env_file:
      - ../../services/service-mailing/.env.development
    command: yarn dev
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    ports:
      - "${SERVICE_REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${SERVICE_REDIS_PASSWORD}
    command: redis-server --requirepass ${SERVICE_REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
