services:
  authentication-service:
    build:
      context: ../../
      dockerfile: services/service-authentication/Dockerfile.development
    ports:
      - "${SERVICE_AUTHENTICATION_PORT}:5001"
    volumes:
      - ../../services/service-authentication/src:/app/src
      - authentication_node_modules:/app/node_modules
    env_file:
      - ../../services/service-authentication/.env.development
    command: yarn dev
    depends_on:
      - redis

  mailing-service:
    build:
      context: ../../
      dockerfile: services/service-mailing/Dockerfile.development
    ports:
      - "${SERVICE_MAILING_PORT}:5002"
    volumes:
      - ../../services/service-mailing/src:/app/src
      - mailing_node_modules:/app/node_modules
    env_file:
      - ../../services/service-mailing/.env.development
    command: yarn dev
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    ports:
      - "${SERVICE_REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${SERVICE_REDIS_PASSWORD}
    command: redis-server --requirepass ${SERVICE_REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  authentication_node_modules:
  mailing_node_modules:
  redis-data:
