services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-my-redis-password} --save 60 1 --loglevel warning
volumes:
  redis-data:
