version: '3.8'
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "mama-redis-1234"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network

volumes:
  redis-data:

networks:
  redis-network:
