version: '3.8'

services:
  authentication-service:
    image: your-dockerhub-username/service-authentication:latest
    ports:
      - '3000:3000'
    env_file:
      - ../../services/service-authentication/.env.production
    depends_on:
      - redis
    restart: unless-stopped

  mailing-service:
    image: your-dockerhub-username/service-mailing:latest
    ports:
      - '4000:4000'
    env_file:
      - ../../services/service-mailing/.env.production
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-prod-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-prod-data:
