version: "3.8"

services:
  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka
    entrypoint: ["/etc/confluent/docker/init.sh"]
    env_file:
      - .env
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
volumes:
  kafka-data:
